/**
 * Generate service worker with pre-cache manifest from Vite build output.
 *
 * Scans dist/ for all built assets and generates dist/sw.js that:
 *   1. Pre-caches all app shell assets (HTML, CSS, JS, JSON, images)
 *   2. Stale-while-revalidate for CDN resources (Chart.js, html2pdf.js)
 *   3. Network-first for navigation, cache-first for assets
 *   4. Auto-invalidates old caches via build hash
 *
 * Runs as post-build: vite build && node scripts/generate-sw.mjs
 */

import { readdirSync, writeFileSync, statSync } from 'fs';
import { resolve, dirname, relative } from 'path';
import { fileURLToPath } from 'url';
import { createHash } from 'crypto';

const __dirname = dirname(fileURLToPath(import.meta.url));
const distDir = resolve(__dirname, '..', 'dist');
const BASE_PATH = '/14to17';

// Collect all files in dist/ (recursive, exclude sw.js itself)
function collectFiles(dir, base = dir) {
  const files = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = resolve(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...collectFiles(full, base));
    } else if (entry.name !== 'sw.js') {
      const rel = relative(base, full).replace(/\\/g, '/');
      const size = statSync(full).size;
      // Skip very large files (>500KB) and source maps
      if (size < 500_000 && !rel.endsWith('.map')) {
        files.push(BASE_PATH + '/' + rel);
      }
    }
  }
  return files;
}

const precacheFiles = collectFiles(distDir);

// Build hash from file list for cache versioning
const hash = createHash('md5')
  .update(precacheFiles.sort().join('\n'))
  .digest('hex')
  .slice(0, 8);

const cacheName = 'career-compass-' + hash;

const sw = [
  '// Generated by scripts/generate-sw.mjs — do not edit manually',
  "const CACHE_NAME = '" + cacheName + "';",
  'const PRECACHE_URLS = ' + JSON.stringify(precacheFiles, null, 2) + ';',
  '',
  "// CDN origins to cache at runtime",
  "const CDN_ORIGINS = ['https://cdn.jsdelivr.net'];",
  '',
  "self.addEventListener('install', (e) => {",
  '  e.waitUntil(',
  '    caches.open(CACHE_NAME)',
  '      .then((cache) => cache.addAll(PRECACHE_URLS))',
  '      .then(() => self.skipWaiting())',
  '  );',
  '});',
  '',
  "self.addEventListener('activate', (e) => {",
  '  e.waitUntil(',
  '    caches.keys()',
  '      .then((keys) => Promise.all(',
  '        keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k))',
  '      ))',
  '      .then(() => self.clients.claim())',
  '  );',
  '});',
  '',
  "self.addEventListener('fetch', (e) => {",
  '  const { request } = e;',
  '  const url = new URL(request.url);',
  '',
  '  // Skip non-GET and non-http requests',
  "  if (request.method !== 'GET') return;",
  "  if (!url.protocol.startsWith('http')) return;",
  '',
  '  // Navigation: network-first, fall back to cached shell',
  "  if (request.mode === 'navigate') {",
  '    e.respondWith(',
  "      fetch(request).catch(() => caches.match('" + BASE_PATH + "/index.html'))",
  '    );',
  '    return;',
  '  }',
  '',
  '  // CDN resources: stale-while-revalidate',
  '  if (CDN_ORIGINS.some((origin) => url.origin === origin)) {',
  '    e.respondWith(',
  '      caches.match(request).then((cached) => {',
  '        const fetchPromise = fetch(request).then((response) => {',
  '          if (response.ok) {',
  '            caches.open(CACHE_NAME).then((cache) => cache.put(request, response.clone()));',
  '          }',
  '          return response;',
  '        }).catch(() => cached);',
  '        return cached || fetchPromise;',
  '      })',
  '    );',
  '    return;',
  '  }',
  '',
  '  // Same-origin assets: cache-first (pre-cached or runtime-cached)',
  '  e.respondWith(',
  '    caches.match(request).then((cached) => {',
  '      if (cached) return cached;',
  '      return fetch(request).then((response) => {',
  '        if (response.ok && url.origin === self.location.origin) {',
  '          caches.open(CACHE_NAME).then((cache) => cache.put(request, response.clone()));',
  '        }',
  '        return response;',
  '      });',
  '    })',
  '  );',
  '});',
  '',
].join('\n');

writeFileSync(resolve(distDir, 'sw.js'), sw, 'utf-8');
console.log('Generated sw.js (cache: ' + cacheName + ', ' + precacheFiles.length + ' pre-cached files)');
